### ISSUE TITLE
How do I call the scan interface?

### ISSUE THREAD

**Issue by xiezhouyan1027** [yelhouti/scan-server#3]
![image](https://github.com/tailosoft/scan-server/assets/57662346/652f88a3-592a-44a0-93ea-bf9062d77781)
This is my equipment list.
How to call the scanning interface?
Is that so?  http://localhost:5000/api/scan/{6BDD1FC6-810F-11D0-BEC7-08002BE2092F}\\0000     
![image](https://github.com/tailosoft/scan-server/assets/57662346/496cb29b-771d-42a0-a368-90e102e0a058)

**Comment by yelhouti** [comment]
Hi sorry for the delay, I updated the doc to answer your question :

https://github.com/tailosoft/scan-server/blob/main/README.md#how-to-use
